version: "2.1"

services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: photonix
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6.2.2

  photonix:
    build: .
    ports:
      - 80:80/tcp
    environment:
      ENV: prd
      POSTGRES_HOST: postgres
      POSTGRES_DB: photonix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      ALLOWED_HOSTS: '*'
    volumes:
      - photos:/data/photos
      - raw-photos-processed:/data/raw-photos-processed
      - cache:/data/cache
      - models:/data/models
    links:
      - postgres
      - redis
    labels:
      - io.balena.features.supervisor-api=1

volumes:
  db:
  photos:
  raw-photos-processed:
  cache:
  models:
